name: Rebuild the admin site on the server
on:
  push:
    branches:
    - testing
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/repos/CHPRIS-Admin
          git pull origin testing
          yarn install
          yarn build
          cp -r build/. /var/www/admin.html/
          systemctl restart apache2.service
